<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'LECG'">
    <SupportedRevitVersions>2026;2027</SupportedRevitVersions>
    <RevitVersion Condition="'$(RevitVersion)' == ''">2026</RevitVersion>
    <BaseOutputPath>bin\$(RevitVersion)\</BaseOutputPath>
    <BaseIntermediateOutputPath>obj\$(RevitVersion)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
